# Generated by Django 5.0.1 on 2024-08-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('batch_year', models.DateField(blank=True, null=True)),
                ('batch', models.TextField(blank=True, max_length=6, null=True)),
                ('category_name', models.TextField(blank=True, max_length=100, null=True)),
                ('attempted', models.IntegerField(blank=True, null=True)),
                ('tests', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
