# Generated by Django 5.0.1 on 2024-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
