# Generated by Django 5.0.1 on 2024-08-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_batch_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='category_name',
        ),
    ]
